version: "3.8"

services:
  mysql-springboot-container:
    image: mysql:8
    container_name: mysql-springboot-container
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/et/mysql/conf.d
    networks:
      - backend

  springboot-docker-container:
    depends_on:
      - mysql-springboot-container
    build: ./
    container_name: springboot-docker-container
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - ./:/app
    networks:
      - backend

volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:

networks:
  backend:
    name: springboot-app-network
